#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("IMInventory.Resource", IsApplication=true)]

namespace IMInventory
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Stripe.Resource.Drawable.amex = global::IMInventory.Resource.Drawable.amex;
			global::Stripe.Resource.Drawable.credit = global::IMInventory.Resource.Drawable.credit;
			global::Stripe.Resource.Drawable.cvc = global::IMInventory.Resource.Drawable.cvc;
			global::Stripe.Resource.Drawable.diners = global::IMInventory.Resource.Drawable.diners;
			global::Stripe.Resource.Drawable.discover = global::IMInventory.Resource.Drawable.discover;
			global::Stripe.Resource.Drawable.jcb = global::IMInventory.Resource.Drawable.jcb;
			global::Stripe.Resource.Drawable.maestro = global::IMInventory.Resource.Drawable.maestro;
			global::Stripe.Resource.Drawable.mastercard = global::IMInventory.Resource.Drawable.mastercard;
			global::Stripe.Resource.Drawable.visa = global::IMInventory.Resource.Drawable.visa;
			global::Stripe.Resource.Id.stripeCvc = global::IMInventory.Resource.Id.stripeCvc;
			global::Stripe.Resource.Id.stripeExpiration = global::IMInventory.Resource.Id.stripeExpiration;
			global::Stripe.Resource.Id.stripeImage = global::IMInventory.Resource.Id.stripeImage;
			global::Stripe.Resource.Id.stripeLastFour = global::IMInventory.Resource.Id.stripeLastFour;
			global::Stripe.Resource.Id.stripeLayoutOne = global::IMInventory.Resource.Id.stripeLayoutOne;
			global::Stripe.Resource.Id.stripeLayoutTwo = global::IMInventory.Resource.Id.stripeLayoutTwo;
			global::Stripe.Resource.Id.stripeNumber = global::IMInventory.Resource.Id.stripeNumber;
			global::Stripe.Resource.Layout.stripeviewlayout = global::IMInventory.Resource.Layout.stripeviewlayout;
			global::Stripe.Resource.String.library_name = global::IMInventory.Resource.String.library_name;
			global::Xamarin.InAppBilling.Resource.String.library_name = global::IMInventory.Resource.String.library_name;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::IMInventory.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::IMInventory.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::IMInventory.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int ColorPrimary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ColorPrimaryDark = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int tabsScrollColor = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int addimage = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int amex = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int appened2x = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int AppIcon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int back = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int back_arrow2x = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int backsignup = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int backtolist = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int barcode = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int barcode2x = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int barcode_entry = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int barcode_icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int barcode_icon2x = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int btn_cancel = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int btn_create = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int btn_login_2x = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int btn_sign_up2x = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int btn_Update = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int btnsignup2x = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int camera_graybox = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Check = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int CreateProject = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int credit = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int customborder = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int customprogressbar = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int cvc = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int delete2x = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int deleteicon = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int deleteicon2x = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int deletelocation2x = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int details2x = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int dictation2x = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int diners = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int discover = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int edit = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int EditTextStyle = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int flash = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int green_tick2x = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int Hamburger = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int helpicon = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int i_m_logo_white = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Icon = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int icon_camera2x = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int icon_save2x = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int icon_voice2x = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int iconmain_screen2x = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int jcb = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int list2x = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int locationdelete2x = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int locationdetails2x = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int locationpopupcloseicon2x = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int locationrename2x = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int logo_2x = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int logout = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int maestro = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int manual_entry2x = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int mastercard = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int next = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ok = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int pause = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int pause_icon2x = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int play = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int prev = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int qrcodegenarator = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int rename2x = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int search2x = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int searchdelete_icon2x = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int spalsh = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int splash = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int upgrade = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int upload = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int uploadlocation = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int visa = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int voice = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int voice_dictation = 2130837578;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0700cb
			public const int AddlblVoiceCamPicName_ = 2131165387;
			
			// aapt resource value: 0x7f0700c9
			public const int Addvoicecam_ = 2131165385;
			
			// aapt resource value: 0x7f0700ca
			public const int Addvoicecampath_ = 2131165386;
			
			// aapt resource value: 0x7f070085
			public const int LayoutManualEntry = 2131165317;
			
			// aapt resource value: 0x7f07009d
			public const int LayoutManualPreview = 2131165341;
			
			// aapt resource value: 0x7f0700c5
			public const int LayoutVoiceEntry = 2131165381;
			
			// aapt resource value: 0x7f0700db
			public const int LayoutVoicePreview = 2131165403;
			
			// aapt resource value: 0x7f070077
			public const int List = 2131165303;
			
			// aapt resource value: 0x7f07007b
			public const int ListLocation = 2131165307;
			
			// aapt resource value: 0x7f070084
			public const int ListLocationItems = 2131165316;
			
			// aapt resource value: 0x7f0700a0
			public const int ManualCamImagePreview = 2131165344;
			
			// aapt resource value: 0x7f07004b
			public const int Text = 2131165259;
			
			// aapt resource value: 0x7f0700ad
			public const int TextClientName = 2131165357;
			
			// aapt resource value: 0x7f0700a8
			public const int TextInventoryDate = 2131165352;
			
			// aapt resource value: 0x7f0700a6
			public const int TextInventoryType = 2131165350;
			
			// aapt resource value: 0x7f0700a7
			public const int TextLocation = 2131165351;
			
			// aapt resource value: 0x7f07004d
			public const int TextLocationItem = 2131165261;
			
			// aapt resource value: 0x7f07004f
			public const int TextLocationItemInventoryDate = 2131165263;
			
			// aapt resource value: 0x7f070050
			public const int TextLocationItemInventoryUnitCost = 2131165264;
			
			// aapt resource value: 0x7f0700aa
			public const int TextProject1 = 2131165354;
			
			// aapt resource value: 0x7f0700ab
			public const int TextProject2 = 2131165355;
			
			// aapt resource value: 0x7f0700de
			public const int VoiceCamImagePreview = 2131165406;
			
			// aapt resource value: 0x7f07007c
			public const int btn1 = 2131165308;
			
			// aapt resource value: 0x7f07000f
			public const int btnBarBacktolist = 2131165199;
			
			// aapt resource value: 0x7f070013
			public const int btnCancelCreateLocation = 2131165203;
			
			// aapt resource value: 0x7f070017
			public const int btnCancelCreateProject = 2131165207;
			
			// aapt resource value: 0x7f07001a
			public const int btnCancelEditLocationFromPopUp = 2131165210;
			
			// aapt resource value: 0x7f070039
			public const int btnCancelSendForgetPassword = 2131165241;
			
			// aapt resource value: 0x7f070012
			public const int btnCreateLocation = 2131165202;
			
			// aapt resource value: 0x7f070016
			public const int btnCreateProject = 2131165206;
			
			// aapt resource value: 0x7f07009e
			public const int btnDiscardPreview = 2131165342;
			
			// aapt resource value: 0x7f070019
			public const int btnEditLocationFromPopUp = 2131165209;
			
			// aapt resource value: 0x7f07009b
			public const int btnManualBacktolist = 2131165339;
			
			// aapt resource value: 0x7f070078
			public const int btnOpenCreateProjectPopUp = 2131165304;
			
			// aapt resource value: 0x7f07005a
			public const int btnRedirectSignup = 2131165274;
			
			// aapt resource value: 0x7f07009c
			public const int btnSave = 2131165340;
			
			// aapt resource value: 0x7f070010
			public const int btnSaveBarCode = 2131165200;
			
			// aapt resource value: 0x7f07009f
			public const int btnSavePreview = 2131165343;
			
			// aapt resource value: 0x7f0700da
			public const int btnSaveVoiceEntryInventory = 2131165402;
			
			// aapt resource value: 0x7f070038
			public const int btnSendForgetPassword = 2131165240;
			
			// aapt resource value: 0x7f070028
			public const int btnUpgrade = 2131165224;
			
			// aapt resource value: 0x7f0700d9
			public const int btnVoiceBacktolist = 2131165401;
			
			// aapt resource value: 0x7f0700dc
			public const int btnVoiceDiscardPreview = 2131165404;
			
			// aapt resource value: 0x7f0700dd
			public const int btnVoiceSavePreview = 2131165405;
			
			// aapt resource value: 0x7f0700a4
			public const int btnclosebusinessuse = 2131165348;
			
			// aapt resource value: 0x7f0700cf
			public const int btnpauserecord = 2131165391;
			
			// aapt resource value: 0x7f07007d
			public const int btnqrgenerate = 2131165309;
			
			// aapt resource value: 0x7f070057
			public const int btnsignin = 2131165271;
			
			// aapt resource value: 0x7f0700ba
			public const int btnsignup = 2131165370;
			
			// aapt resource value: 0x7f0700ce
			public const int btnstartrecord = 2131165390;
			
			// aapt resource value: 0x7f070089
			public const int cam1 = 2131165321;
			
			// aapt resource value: 0x7f07008a
			public const int cam1path = 2131165322;
			
			// aapt resource value: 0x7f07008c
			public const int cam2 = 2131165324;
			
			// aapt resource value: 0x7f07008d
			public const int cam2path = 2131165325;
			
			// aapt resource value: 0x7f07008f
			public const int cam3 = 2131165327;
			
			// aapt resource value: 0x7f070090
			public const int cam3path = 2131165328;
			
			// aapt resource value: 0x7f070092
			public const int cam4 = 2131165330;
			
			// aapt resource value: 0x7f070093
			public const int cam4path = 2131165331;
			
			// aapt resource value: 0x7f0700df
			public const int contentFrame = 2131165407;
			
			// aapt resource value: 0x7f07001c
			public const int content_frame = 2131165212;
			
			// aapt resource value: 0x7f070054
			public const int email_login_form = 2131165268;
			
			// aapt resource value: 0x7f0700d6
			public const int fastforward = 2131165398;
			
			// aapt resource value: 0x7f07004c
			public const int hdnInventoryID = 2131165260;
			
			// aapt resource value: 0x7f07003d
			public const int helpwebView = 2131165245;
			
			// aapt resource value: 0x7f07001e
			public const int imgAppLogo = 2131165214;
			
			// aapt resource value: 0x7f07003e
			public const int imgCloseLocationCountPopUp = 2131165246;
			
			// aapt resource value: 0x7f070045
			public const int imgCloseLocationEditPopUp = 2131165253;
			
			// aapt resource value: 0x7f070065
			public const int imgCreateProjectFromMain = 2131165285;
			
			// aapt resource value: 0x7f070076
			public const int imgDeleteVoiceSearch = 2131165302;
			
			// aapt resource value: 0x7f0700a5
			public const int imgEditLocation = 2131165349;
			
			// aapt resource value: 0x7f07007a
			public const int imgLocationBack = 2131165306;
			
			// aapt resource value: 0x7f07007e
			public const int imgLocationListItemBack = 2131165310;
			
			// aapt resource value: 0x7f070067
			public const int imgNDCheck = 2131165287;
			
			// aapt resource value: 0x7f070068
			public const int imgNDHelp = 2131165288;
			
			// aapt resource value: 0x7f070066
			public const int imgNDLogOut = 2131165286;
			
			// aapt resource value: 0x7f070024
			public const int imgNDTabLogOut = 2131165220;
			
			// aapt resource value: 0x7f0700d4
			public const int imgPausePlayer = 2131165396;
			
			// aapt resource value: 0x7f0700d5
			public const int imgPlayPlayer = 2131165397;
			
			// aapt resource value: 0x7f070008
			public const int imgScanBarcode = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int imgScanBarcodeSmall = 2131165195;
			
			// aapt resource value: 0x7f070073
			public const int imgSearchBack = 2131165299;
			
			// aapt resource value: 0x7f070025
			public const int imgTabNDCheck = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int imgTabNDHelp = 2131165222;
			
			// aapt resource value: 0x7f070075
			public const int imgVoiceSearch = 2131165301;
			
			// aapt resource value: 0x7f0700d0
			public const int imgdeletedrecord = 2131165392;
			
			// aapt resource value: 0x7f070021
			public const int imgflashicon = 2131165217;
			
			// aapt resource value: 0x7f07003b
			public const int imghelpBack = 2131165243;
			
			// aapt resource value: 0x7f07005b
			public const int imglist = 2131165275;
			
			// aapt resource value: 0x7f07001d
			public const int imglistinternal = 2131165213;
			
			// aapt resource value: 0x7f0700d3
			public const int imgrewind = 2131165395;
			
			// aapt resource value: 0x7f0700d1
			public const int imgsaverecord = 2131165393;
			
			// aapt resource value: 0x7f070022
			public const int imgsearchicon = 2131165218;
			
			// aapt resource value: 0x7f0700af
			public const int imgsignupback = 2131165359;
			
			// aapt resource value: 0x7f0700c2
			public const int imgtermsBack = 2131165378;
			
			// aapt resource value: 0x7f07001f
			public const int layoutheader = 2131165215;
			
			// aapt resource value: 0x7f07008b
			public const int lblCam1PicName = 2131165323;
			
			// aapt resource value: 0x7f07008e
			public const int lblCam2PicName = 2131165326;
			
			// aapt resource value: 0x7f070091
			public const int lblCam3PicName = 2131165329;
			
			// aapt resource value: 0x7f070094
			public const int lblCam4PicName = 2131165332;
			
			// aapt resource value: 0x7f070081
			public const int lblListItemDescription = 2131165313;
			
			// aapt resource value: 0x7f070082
			public const int lblListItemQuantity = 2131165314;
			
			// aapt resource value: 0x7f070083
			public const int lblListItemUnitCost = 2131165315;
			
			// aapt resource value: 0x7f070080
			public const int lblLocationListHeading = 2131165312;
			
			// aapt resource value: 0x7f07002a
			public const int lblNDOptionsAlert = 2131165226;
			
			// aapt resource value: 0x7f07006c
			public const int lblNDOptionsScanViaBluetooth = 2131165292;
			
			// aapt resource value: 0x7f070029
			public const int lblNDOptionsText = 2131165225;
			
			// aapt resource value: 0x7f07002e
			public const int lblNDOptionsUploadOnWifi = 2131165230;
			
			// aapt resource value: 0x7f07002c
			public const int lblNDOptionsVibration = 2131165228;
			
			// aapt resource value: 0x7f0700d8
			public const int lblPlayingCount = 2131165400;
			
			// aapt resource value: 0x7f070030
			public const int lblTabNDOptionsScanViaBluetooth = 2131165232;
			
			// aapt resource value: 0x7f0700b8
			public const int lblaccept = 2131165368;
			
			// aapt resource value: 0x7f070004
			public const int lblbluetoothscan = 2131165188;
			
			// aapt resource value: 0x7f070058
			public const int lblforgotpassword = 2131165272;
			
			// aapt resource value: 0x7f070059
			public const int lblmember = 2131165273;
			
			// aapt resource value: 0x7f070052
			public const int lblprojectname = 2131165266;
			
			// aapt resource value: 0x7f070007
			public const int lblscanbarcode = 2131165191;
			
			// aapt resource value: 0x7f0700a2
			public const int lblsignupsubhead = 2131165346;
			
			// aapt resource value: 0x7f0700a3
			public const int lblsignupsubtext = 2131165347;
			
			// aapt resource value: 0x7f0700b9
			public const int lblterm = 2131165369;
			
			// aapt resource value: 0x7f070023
			public const int leftListView = 2131165219;
			
			// aapt resource value: 0x7f070051
			public const int ll1 = 2131165265;
			
			// aapt resource value: 0x7f070053
			public const int ll2 = 2131165267;
			
			// aapt resource value: 0x7f070064
			public const int llCreateNewProject = 2131165284;
			
			// aapt resource value: 0x7f0700cc
			public const int llVoiceImageView = 2131165388;
			
			// aapt resource value: 0x7f070009
			public const int llafterscan = 2131165193;
			
			// aapt resource value: 0x7f070060
			public const int llbar = 2131165280;
			
			// aapt resource value: 0x7f070062
			public const int llfindit = 2131165282;
			
			// aapt resource value: 0x7f07005c
			public const int llmanu = 2131165276;
			
			// aapt resource value: 0x7f0700d2
			public const int llplayer = 2131165394;
			
			// aapt resource value: 0x7f070006
			public const int llscanbarcode = 2131165190;
			
			// aapt resource value: 0x7f07005e
			public const int llvoice = 2131165278;
			
			// aapt resource value: 0x7f0700a9
			public const int locationId = 2131165353;
			
			// aapt resource value: 0x7f07004e
			public const int locationitemId = 2131165262;
			
			// aapt resource value: 0x7f07007f
			public const int locationlistitemlayoutheader = 2131165311;
			
			// aapt resource value: 0x7f07001b
			public const int myDrawer = 2131165211;
			
			// aapt resource value: 0x7f0700a1
			public const int paymentwebView = 2131165345;
			
			// aapt resource value: 0x7f0700d7
			public const int playerseekbar = 2131165399;
			
			// aapt resource value: 0x7f070079
			public const int prgUpload = 2131165305;
			
			// aapt resource value: 0x7f0700b7
			public const int rdbBusinessUse = 2131165367;
			
			// aapt resource value: 0x7f0700b6
			public const int rdbFreeUse = 2131165366;
			
			// aapt resource value: 0x7f070046
			public const int rlAddLocation = 2131165254;
			
			// aapt resource value: 0x7f070048
			public const int rlDeleteLocation = 2131165256;
			
			// aapt resource value: 0x7f070049
			public const int rlDetailsLocation = 2131165257;
			
			// aapt resource value: 0x7f07004a
			public const int rlListLocationItem = 2131165258;
			
			// aapt resource value: 0x7f070047
			public const int rlRenameLocation = 2131165255;
			
			// aapt resource value: 0x7f070000
			public const int scrdata = 2131165184;
			
			// aapt resource value: 0x7f0700c1
			public const int stripeCvc = 2131165377;
			
			// aapt resource value: 0x7f0700c0
			public const int stripeExpiration = 2131165376;
			
			// aapt resource value: 0x7f0700bb
			public const int stripeImage = 2131165371;
			
			// aapt resource value: 0x7f0700bf
			public const int stripeLastFour = 2131165375;
			
			// aapt resource value: 0x7f0700bc
			public const int stripeLayoutOne = 2131165372;
			
			// aapt resource value: 0x7f0700be
			public const int stripeLayoutTwo = 2131165374;
			
			// aapt resource value: 0x7f0700bd
			public const int stripeNumber = 2131165373;
			
			// aapt resource value: 0x7f070069
			public const int swNDOptionsAlert = 2131165289;
			
			// aapt resource value: 0x7f07006d
			public const int swNDOptionsScanViaBlutooth = 2131165293;
			
			// aapt resource value: 0x7f07006b
			public const int swNDOptionsUploadOnWifi = 2131165291;
			
			// aapt resource value: 0x7f07006a
			public const int swNDOptionsVibration = 2131165290;
			
			// aapt resource value: 0x7f07002b
			public const int swTabNDOptionsAlert = 2131165227;
			
			// aapt resource value: 0x7f070031
			public const int swTabNDOptionsScanViaBlutooth = 2131165233;
			
			// aapt resource value: 0x7f07002f
			public const int swTabNDOptionsUploadOnWifi = 2131165231;
			
			// aapt resource value: 0x7f07002d
			public const int swTabNDOptionsVibration = 2131165229;
			
			// aapt resource value: 0x7f070005
			public const int swscanbluetooth = 2131165189;
			
			// aapt resource value: 0x7f070020
			public const int tabTextHeader = 2131165216;
			
			// aapt resource value: 0x7f0700ac
			public const int textId = 2131165356;
			
			// aapt resource value: 0x7f0700ae
			public const int textView1 = 2131165358;
			
			// aapt resource value: 0x7f070044
			public const int txtBarcodeEntryCount = 2131165252;
			
			// aapt resource value: 0x7f070043
			public const int txtBarcodeEntryCountText = 2131165251;
			
			// aapt resource value: 0x7f070096
			public const int txtBrand = 2131165334;
			
			// aapt resource value: 0x7f070087
			public const int txtClientName = 2131165319;
			
			// aapt resource value: 0x7f070015
			public const int txtCreateProjectClientName = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int txtCreateProjectName = 2131165204;
			
			// aapt resource value: 0x7f070018
			public const int txtEditPopUpLocationName = 2131165208;
			
			// aapt resource value: 0x7f07003c
			public const int txtHelpScreenheading = 2131165244;
			
			// aapt resource value: 0x7f070095
			public const int txtItemDescription = 2131165333;
			
			// aapt resource value: 0x7f070088
			public const int txtLocation = 2131165320;
			
			// aapt resource value: 0x7f070040
			public const int txtManualEntryCount = 2131165248;
			
			// aapt resource value: 0x7f07003f
			public const int txtManualEntryCountText = 2131165247;
			
			// aapt resource value: 0x7f070098
			public const int txtModelNumber = 2131165336;
			
			// aapt resource value: 0x7f070072
			public const int txtNDAddress = 2131165298;
			
			// aapt resource value: 0x7f07006f
			public const int txtNDCompanyName = 2131165295;
			
			// aapt resource value: 0x7f070070
			public const int txtNDEmail = 2131165296;
			
			// aapt resource value: 0x7f070071
			public const int txtNDMobile = 2131165297;
			
			// aapt resource value: 0x7f07006e
			public const int txtNDName = 2131165294;
			
			// aapt resource value: 0x7f07009a
			public const int txtNotes = 2131165338;
			
			// aapt resource value: 0x7f070056
			public const int txtPassword = 2131165270;
			
			// aapt resource value: 0x7f070037
			public const int txtPopUpForgotpasswordEmailID = 2131165239;
			
			// aapt resource value: 0x7f070011
			public const int txtPopUpLocationName = 2131165201;
			
			// aapt resource value: 0x7f070086
			public const int txtProjectName = 2131165318;
			
			// aapt resource value: 0x7f070097
			public const int txtQuantity = 2131165335;
			
			// aapt resource value: 0x7f0700b3
			public const int txtSignUpEmail = 2131165363;
			
			// aapt resource value: 0x7f0700b0
			public const int txtSignUpFirstName = 2131165360;
			
			// aapt resource value: 0x7f0700b1
			public const int txtSignUpLastName = 2131165361;
			
			// aapt resource value: 0x7f0700b4
			public const int txtSignUpPassword = 2131165364;
			
			// aapt resource value: 0x7f0700b5
			public const int txtSignUpRePassword = 2131165365;
			
			// aapt resource value: 0x7f0700b2
			public const int txtSignUpUserName = 2131165362;
			
			// aapt resource value: 0x7f070036
			public const int txtTabNDAddress = 2131165238;
			
			// aapt resource value: 0x7f070033
			public const int txtTabNDCompanyName = 2131165235;
			
			// aapt resource value: 0x7f070034
			public const int txtTabNDEmail = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int txtTabNDMobile = 2131165237;
			
			// aapt resource value: 0x7f070032
			public const int txtTabNDName = 2131165234;
			
			// aapt resource value: 0x7f0700c3
			public const int txtTermsScreenheading = 2131165379;
			
			// aapt resource value: 0x7f070099
			public const int txtUnitCost = 2131165337;
			
			// aapt resource value: 0x7f070027
			public const int txtUpgrade = 2131165223;
			
			// aapt resource value: 0x7f070055
			public const int txtUserName = 2131165269;
			
			// aapt resource value: 0x7f070042
			public const int txtVoiceLength = 2131165250;
			
			// aapt resource value: 0x7f070041
			public const int txtVoiceLengthText = 2131165249;
			
			// aapt resource value: 0x7f070002
			public const int txtbarClientName = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int txtbarLocation = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int txtbarProjectname = 2131165185;
			
			// aapt resource value: 0x7f07000a
			public const int txtbarbarcodenumber = 2131165194;
			
			// aapt resource value: 0x7f070061
			public const int txtbarcodeentry = 2131165281;
			
			// aapt resource value: 0x7f07000c
			public const int txtbaritemname = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int txtbarquantity = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int txtbarunitcost = 2131165198;
			
			// aapt resource value: 0x7f070063
			public const int txtfindit = 2131165283;
			
			// aapt resource value: 0x7f07005d
			public const int txtmanualentry = 2131165277;
			
			// aapt resource value: 0x7f0700cd
			public const int txtrecordtime = 2131165389;
			
			// aapt resource value: 0x7f070074
			public const int txtsearchproject = 2131165300;
			
			// aapt resource value: 0x7f0700c7
			public const int txtvoiceclientname = 2131165383;
			
			// aapt resource value: 0x7f07005f
			public const int txtvoicedictation = 2131165279;
			
			// aapt resource value: 0x7f0700c8
			public const int txtvoicelocation = 2131165384;
			
			// aapt resource value: 0x7f0700c6
			public const int txtvoiceprojectname = 2131165382;
			
			// aapt resource value: 0x7f0700c4
			public const int webView = 2131165380;
			
			// aapt resource value: 0x7f07003a
			public const int wvGoogleSignIn = 2131165242;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BarcodeEntry = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreateLocation = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CreateProject = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditLocation = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EditLocationFromPopUp = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int EntryTab = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ForgotPassword = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int GoogleDriveWebView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Help = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int LocationDetails = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int LocationEditPopUp = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int LocationListItem = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Login = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Main = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Main_Search_A = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int MainInventoryList = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int MainLocationListItem = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int ManualEntry = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int Payment = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int PopUpWindow = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int SearchLocation = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int SearchProject = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int SearchProject_Design = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int Signup = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int stripeviewlayout = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int Terms = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int test = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int test1 = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int VoiceDictation = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int zxingscanneractivitylayout = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int zxingscannerfragmentlayout = 2130903070;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
